// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define([], function() {
    var Uploader;
    Uploader = (function() {

      function Uploader() {
        this.onSuccess = __bind(this.onSuccess, this);

        var _this = this;
        this.endpoint = "//localhost:8090/upload";
        this.message = $("<div />").addClass("upload-message").html('<h1>Drop a file to upload..</h1\n\n<p>\n  Currently only collada <code>.dae</code> is supported, and materials and textures are discarded.\n</p>').appendTo('body');
        this.overlay = $("<div />").addClass('upload-overlay').appendTo('body');
        this.form = $("<form method='post' enctype='multipart/form-data' action='" + this.endpoint + "' />").addClass('upload-form').html('<input type="file" name="upload" />').appendTo('body');
        this.form.find('input').change(function() {
          _this.submit();
          return setTimeout(function() {
            _this.form.hide();
            _this.overlay.hide();
            return _this.message.hide();
          }, 50);
        });
      }

      Uploader.prototype.onSuccess = function() {
        return alert("file upload complete..");
      };

      Uploader.prototype.submit = function() {
        var file;
        file = this.form.find('input').get(0).files[0];
        if (!file.name.match(/dae$/i)) {
          alert("Sorry, only files of type .dae (collada) are able to be uploaded...");
          return;
        }
        return $.ajax({
          type: "post",
          url: this.endpoint,
          data: new FormData(this.form.get(0)),
          processData: false,
          contentType: false,
          success: this.onSuccess,
          error: function() {
            return alert("wtf?");
          },
          xhrFields: {
            onprogress: function(progress) {
              var percentage;
              percentage = Math.floor((progress.total / progress.totalSize) * 100);
              console.log('progress', percentage);
              if (percentage === 100) {
                return console.log('DONE!');
              }
            }
          }
        });
      };

      return Uploader;

    })();
    return Uploader;
  });

}).call(this);
